---
 - hosts: web
   remote_user: root
   ignore_errors: yes
   tasks: 
             - name: create a user  
               user:
                   name: u7092020
                   comment: carlos Monte
             - name: create file on target host
               file: 
                   path: /tmp/ansiblefile
                   state: touch
             - name: create a directory
               file:
                   path: /opt/directory_ansible
                   state: directory
             - name: install apache    
               yum: 
                  name: httpd
                  state: present
             - name: start service
               service:
                  name: httpd
                  state: started
